import { v } from 'convex/values';
import { internalMutation } from './_generated/server';
import { internal } from './_generated/api';
import { Doc } from './_generated/dataModel';

/**
 * Session-based hourly pay.
 *
 * The driver session (shift check-in → check-out) is the unit of hourly
 * work, not the dispatch leg: legs door-to-door double-count overlapping
 * loads and guess from scheduled windows, while the session is the driver's
 * actual on-the-clock time — and `endSessionInternal` already computes
 * `totalActiveMinutes` on every end path.
 *
 * One payable per completed session, generated by `paySession` (scheduled
 * from endSessionInternal, swept by the daily backstop cron):
 *   - quantity = session hours, rate from the profile's SESSION_DURATION rules
 *   - work-start for settlement windowing = session.startedAt
 *     (see lib/settlementShared.resolveWorkStartTimestamp)
 *   - idempotent via the loadPayables.by_session index
 *   - sessions ended by auto_timeout (driver forgot to check out; capped at
 *     18h by the sweep cron) carry a warningMessage, which surfaces as the
 *     "Load pay" hard blocker — the statement parks in Needs attention until
 *     a human verifies the hours.
 *
 * Drivers whose profile has no SESSION_DURATION rule are untouched — this
 * activates per pay profile, not globally.
 */
export const paySession = internalMutation({
  args: { sessionId: v.id('driverSessions') },
  returns: v.null(),
  handler: async (ctx, args) => {
    const session = await ctx.db.get(args.sessionId);
    if (!session || session.status !== 'completed' || !session.endedAt) return null;

    // One payable per session — the by_session index is the idempotency key.
    const existing = await ctx.db
      .query('loadPayables')
      .withIndex('by_session', (q) => q.eq('sessionId', args.sessionId))
      .first();
    if (existing) return null;

    const driver = await ctx.db.get(session.driverId);
    if (!driver || driver.isDeleted === true) return null;

    const assignments = await ctx.db
      .query('driverProfileAssignments')
      .withIndex('by_driver', (q) => q.eq('driverId', session.driverId))
      .collect();
    if (assignments.length === 0) return null;
    const chosen = assignments.find((a) => a.isDefault) ?? assignments[0];

    const profile = await ctx.db.get(chosen.profileId);
    if (!profile || !profile.isActive) return null;

    const rules = await ctx.db
      .query('rateRules')
      .withIndex('by_profile', (q) => q.eq('profileId', chosen.profileId))
      .collect();
    const sessionRules = rules.filter((r) => r.isActive && r.triggerEvent === 'SESSION_DURATION');
    if (sessionRules.length === 0) return null;

    const minutes =
      session.totalActiveMinutes ?? Math.round((session.endedAt - session.startedAt) / 60000);
    const hours = Math.round((minutes / 60) * 100) / 100;
    if (hours <= 0) return null;

    const dateLabel = new Date(session.startedAt).toLocaleDateString('en-US', {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
    });
    const warningMessage =
      session.endReason === 'auto_timeout'
        ? 'Session auto-timed out — verify hours before approval'
        : undefined;
    const now = Date.now();

    for (const rule of sessionRules) {
      // minThreshold: "only applies after N hours"; maxCap caps the amount.
      if (rule.minThreshold != null && hours < rule.minThreshold) continue;
      let amount = hours * rule.rateAmount;
      if (rule.maxCap != null) amount = Math.min(amount, rule.maxCap);
      amount = Math.round(amount * 100) / 100;

      await ctx.db.insert('loadPayables', {
        driverId: session.driverId,
        sessionId: session._id,
        description: `${rule.name} — ${dateLabel}`,
        quantity: hours,
        rate: rule.rateAmount,
        totalAmount: amount,
        sourceType: 'SYSTEM',
        category: 'EARNING',
        isLocked: false,
        ruleId: rule._id,
        warningMessage,
        workosOrgId: session.organizationId,
        createdAt: now,
        createdBy: 'system:session-pay',
      });
    }
    return null;
  },
});

/**
 * Daily backstop: catch any completed session from the last 7 days that
 * never got its payable (missed hook, transient failure). paySession is
 * idempotent and no-ops for drivers without SESSION_DURATION rules, so
 * re-scheduling broadly is safe.
 */
export const backstopSweep = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const cutoff = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = await ctx.db
      .query('driverSessions')
      .withIndex('by_status_started', (q) =>
        q.eq('status', 'completed').gte('startedAt', cutoff),
      )
      .take(500);

    let scheduled = 0;
    for (const session of recent as Array<Doc<'driverSessions'>>) {
      const paid = await ctx.db
        .query('loadPayables')
        .withIndex('by_session', (q) => q.eq('sessionId', session._id))
        .first();
      if (paid) continue;
      await ctx.scheduler.runAfter(scheduled * 100, internal.sessionPay.paySession, {
        sessionId: session._id,
      });
      scheduled++;
    }
    return null;
  },
});
